name: pca_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - scikit-learn=1.0.2
  - scikit-image=0.19.2
  - simpleitk=2.1.0
  - matplotlib=3.5.1
  - numpy=1.22.2
  - pandas=1.4.1
  - pip
  - pip:
    - tensorflow==2.8.0
    - Keras-Applications==1.0.8
    - classification-models-3D==1.0.3
    - efficientnet-3D==1.0.2
    - segmentation-models-3D==1.0.3
    - tensorflow-addons==0.17.0
    - pydot==1.4.2
    - graphviz==0.20